<?php

/**
 * Implements hook_install().
 */

function mobile_js_redirect_install() {
  variable_set('mobile_js_redirect_enable', 0);
  variable_set('mobile_js_domain_redirect', '');
  variable_set('mobile_js_desktop_domain', '');
}

/**
 * Implements hook_uninstall().
 */

function mobile_js_redirect_uninstall() {
  variable_del('mobile_js_redirect_enable');
  variable_del('mobile_js_domain_redirect');
}