<?php

/**
 * Implements hook_init().
 */

function mobile_js_redirect_init() {
  if (user_is_anonymous()) {
    drupal_add_js('misc/jquery.cookie.js', 'file');
  }

  if (variable_get('mobile_js_redirect_enable', 0)) {
    // add data to Drupal.settings
    global $cookie_domain;
    drupal_add_js(array('mobile_js_redirect' => array('base_domain' => $cookie_domain, 'mobile_domain' => variable_get('mobile_js_domain_redirect', ''), 'desktop_domain' => variable_get('mobile_js_desktop_domain', ''))), 'setting');
    drupal_add_js(drupal_get_path('module', 'mobile_js_redirect') . '/js/mobile_redirect.js', array('weight' => 1000));
  }
}

/**
 * Implements hook_menu().
 */

function mobile_js_redirect_menu() {
  $items['admin/config/system/mobile_js_redirect'] = array(
    'title' => 'Mobile Javascript Redirect',
    'description' => 'Manage settings for mobile redirection via Javascript.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mobile_js_redirect_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mobile_js_redirect.admin.inc',
  );

  return $items;
}